version: "3"
services:
  eventhub:
    image: quay.io/olesku/eventhub:latest
    environment:
      - DISABLE_AUTH=1
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
